# Generated by Django 3.2.7 on 2021-11-16 19:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descript', models.CharField(max_length=3000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatsC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hp', models.PositiveIntegerField(null=True)),
                ('Str', models.PositiveIntegerField(null=True)),
                ('Dex', models.PositiveIntegerField(null=True)),
                ('Con', models.PositiveIntegerField(null=True)),
                ('Int', models.PositiveIntegerField(null=True)),
                ('Wis', models.PositiveIntegerField(null=True)),
                ('Cha', models.PositiveIntegerField(null=True)),
                ('Walk', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hp', models.PositiveIntegerField(null=True)),
                ('Str', models.PositiveIntegerField(null=True)),
                ('Dex', models.PositiveIntegerField(null=True)),
                ('Con', models.PositiveIntegerField(null=True)),
                ('Int', models.PositiveIntegerField(null=True)),
                ('Wis', models.PositiveIntegerField(null=True)),
                ('Cha', models.PositiveIntegerField(null=True)),
                ('Walk', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.CharField(max_length=3000)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('descript', models.CharField(max_length=10000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.statsm')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000, null=True)),
                ('monster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.monster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('descript', models.CharField(max_length=10000)),
                ('race', models.CharField(choices=[('Human', 'Human'), ('Elf', 'Elf'), ('Dark Elf', 'Dark Elf'), ('Dwarf', 'Dwarf'), ('Halfling', 'Halfling'), ('Teifling', 'Teifling'), ('Aarakocra', 'Aarakocra'), ('Dragonborn', 'Dragonborn'), ('Genasi', 'Genasi'), ('Gnome', 'Gnome'), ('Goliath', 'Goliath'), ('Half-Elf', 'Half-Elf'), ('Half-Orc', 'Half-Orc'), ('Aasimar', 'Aasimar')], max_length=200, null=True)),
                ('classes', models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.statsc')),
            ],
        ),
    ]
