# Generated by Django 3.2.7 on 2021-11-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211118_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.campaign'),
        ),
    ]
